/:
    template: home
    data:
        content: home.md
        churches: churches.yml

/churches:
    template: churches/overview
    data:
        churches: churches.yml

/churches/{id}:
    template: churches/detail
    data:
#        intro: intro.md
        church: churches.yml



#/churches:
#    template: churches/overview
#    data:
#        churches: churches/
#
#/churches/{id}:
#    template: churches/detail
#    data:
#        church: churches/
