services:

    yamlParser:
        class: Symfony\Component\Yaml\Yaml
    markdownParser:
        class: \Parsedown
    sassParser:
        class: Leafo\ScssPhp\Compiler
        calls:
            - [addImportPath, ['%rootDirectory%']]

    imageScaler:
        class: Pageon\Html\Image\FixedWidthScaler
        arguments:
            - [200]
    imageFactory:
        class: Pageon\Html\Image\ImageFactory
        arguments:
            - '%sourceDirectory%'
            - '%publicDirectory%'
            - '@imageScaler'

    variableFactory:
        class: Stitcher\Variable\VariableFactory
        calls:
            - ['setYamlParser', ['@yamlParser']]
            - ['setMarkdownParser', ['@markdownParser']]
            - ['setImageParser', ['@imageFactory']]
    variableParser:
        class: Stitcher\Variable\VariableParser
        arguments:
            - '@variableFactory'

    adapterFactory:
        class: Stitcher\Page\Adapter\AdapterFactory
        arguments:
            - '@variableParser'

    cssExtension:
        class: Stitcher\Renderer\Extension\Css
        arguments:
            - '%publicDirectory%'
            - '@sassParser'
    jsExtension:
        class: Stitcher\Renderer\Extension\Js
        arguments:
            - '%publicDirectory%'
    rendererFactory:
        class: Stitcher\Renderer\RendererFactory
        arguments:
            - '%templateDirectory%'
            - '%templateRenderer%'
        calls:
            - ['addExtension', ['@cssExtension']]
            - ['addExtension', ['@jsExtension']]
    renderer:
        factory: 'Stitcher\Renderer\RendererFactory:create'
        arguments:
            - '%templateDirectory%'

    pageFactory:
        class: Stitcher\Page\PageFactory
        arguments:
            - '@variableParser'
    pageParser:
        class: Stitcher\Page\PageParser
        arguments:
            - '@pageFactory'
            - '@adapterFactory'
    pageRenderer:
        class: Stitcher\Page\PageRenderer
        arguments:
            - '@renderer'

    parse:
        class: Stitcher\Task\Parse
        arguments:
            - '%publicDirectory%'
            - '%configurationFile%'
            - '@pageParser'
            - '@pageRenderer'
        calls:
            - ['addSubTask', ['@copyStaticFiles']]
    parsePartial:
        class: Stitcher\Task\PartialParse
        arguments:
            - '%publicDirectory%'
            - '%configurationFile%'
            - '@pageParser'
            - '@pageRenderer'
            - '@copyStaticFiles'
        calls:
            - ['addSubTask', ['@copyStaticFiles']]
    copyStaticFiles:
        class: Stitcher\Task\CopyStaticFiles
        arguments:
            - '%publicDirectory%'
            - '%staticFiles%'
            - '%cacheStaticFiles%'

    developmentServer:
        class: Stitcher\Application\DevelopmentServer
        arguments:
            - '%publicDirectory%'
            - '@parsePartial'
    productionServer:
        class: Stitcher\Application\ProductionServer
        arguments:
            - '%publicDirectory%'

    router:
        class: Stitcher\Application\Router
        arguments:
            - '@routeCollector'
    routeParser:
        class: FastRoute\RouteParser\Std
    routeDataGenerator:
        class: FastRoute\DataGenerator\GroupCountBased
    routeCollector:
        class: FastRoute\RouteCollector
        arguments: ['@routeParser', '@routeDataGenerator']
