/:
    template: home

/guide:
    template: guide
    data:
        guide: guide.md

/examples:
    template: examples/overview
    data:
        collection: collection.yml
        #folderCollection: folder/

/examples/{id}:
    template: examples/detail
    data:
        example:
            src: collection.yml
            id: id
