directories:
    src: ./src
    public: ./public
    data: ./src/data
    cache: ./.cache

image:
    dimensions:
        960x640: { width: 690, height: 640}
        1024x768: { width: 1024, height: 768}
        1920x1080: { width: 1920, height: 1080}
        1600x1200: { width: 1600, height: 1200}
